mvz/alexandria-book-collection-manager

share/alexandria/glade/acquire_dialog__builder.glade, share/alexandria/glade/book_properties_dialog__builder.glade, share/alexandria/glade/new_book_dialog__builder.glade, share/alexandria/glade/preferences_dialog__builder.glade
This should silence warnings about "GtkDialog mapped without a transient parent. This is discouraged."
=> Set initial visibility for dialogs to False

lib/alexandria/ui/export_dialog.rb
Just assume library formats are defined properly instead of aborting early. Somehow this detection of defined formats didn't work properly.
This fixes #38.
=> Fix crash on export

lib/alexandria/book_providers.rb, lib/alexandria/book_providers/z3950.rb, lib/alexandria/import_library.rb, lib/alexandria/import_library_csv.rb, lib/alexandria/ui/alert_dialog.rb, lib/alexandria/ui/bad_isbns_dialog.rb, lib/alexandria/ui/callbacks.rb, lib/alexandria/ui/confirm_erase_dialog.rb, lib/alexandria/ui/conflict_while_copying_dialog.rb, lib/alexandria/ui/error_dialog.rb, lib/alexandria/ui/export_dialog.rb, lib/alexandria/ui/import_dialog.rb, lib/alexandria/ui/keep_bad_isbn_dialog.rb, lib/alexandria/ui/new_provider_dialog.rb, lib/alexandria/ui/new_smart_library_dialog.rb, lib/alexandria/ui/provider_preferences_base_dialog.rb, lib/alexandria/ui/provider_preferences_dialog.rb, lib/alexandria/ui/really_delete_dialog.rb, lib/alexandria/ui/skip_entry_dialog.rb, lib/alexandria/ui/smart_library_properties_dialog.rb, lib/alexandria/ui/smart_library_properties_dialog_base.rb, spec/alexandria/library_spec.rb, spec/alexandria/ui/import_dialog_spec.rb, spec/alexandria/ui/new_provider_dialog_spec.rb, spec/alexandria/ui/new_smart_library_dialog_spec.rb, spec/alexandria/ui/provider_preferences_dialog_spec.rb, spec/alexandria/ui/smart_library_properties_dialog_spec.rb
Using SimpleDelegator makes debugging with Pry super-hard. It was used in Alexandria as a kind of inheritance mechanism instead of a decorator. Instead, use regular composition with explicit delegation where needed.
=> Remove use of SimpleDelegator

spec/spec_helper.rb
- Depend on Bundler to set the load path correctly; specs should be run inside `bundle exec`
- Require `rspec` explicitly since we refer to RSpec in this file
- Simplify code to set `LIBDIR` by using modern `__dir__` instead of `__FILE__`, which is available in all supported Ruby versions
=> Improve spec helper

lib/alexandria/book_providers/amazon_ecs_util.rb, lib/alexandria/ui/keep_bad_isbn_dialog.rb, lib/alexandria/ui/sidepane_manager.rb, share/alexandria/glade/main_app__builder.glade
This cleans up some messages so translations will require a bit less work and
are cleaner.
- Remove useless check for block
The yield will already raise an exception if no block is given, so there's
no point in first checking that ourselves.
- Remove trailing space from message
- Remove unused labels from main app UI
- Remove extra space from message text
=> Clean up some translatable messages

spec/end_to_end/basic_run_spec.rb
Sending keyboard events does not work on Wayland.
=> Do not use Ctrl-q in end-to-end tests

lib/alexandria/ui/ui_manager.rb
This stops the following warning from appearing:
> Window [ID] is a temporary window without parent, application will not be able to position it on screen.
=> Modernize menu popup code to avoid warnings

lib/alexandria/ui/init.rb, spec/alexandria/ui/ui_manager_spec.rb
Before this change, calling #freeze twice would loose the original model.
=> Make #freeze and #unfreeze idempotent

lib/alexandria/ui/alert_dialog.rb
The message should be shown if it exists, and special HTML entities must be escaped.
=> Fix logic for showing extra message in AlertDialog

.rubocop_todo.yml, spec/alexandria/export_library_spec.rb, spec/alexandria/library_spec.rb, spec/alexandria/library_store_spec.rb, spec/alexandria/scanners/cue_cat_spec.rb, spec/alexandria/ui/confirm_erase_dialog_spec.rb, spec/alexandria/ui/skip_entry_dialog_spec.rb, spec/spec_helper.rb
- Use custom be_an_existing_file matcher
- Silence RSpec/PredicateMatcher offenses
=> Fix RSpec/PredicateMatcher offenses

lib/alexandria/ui/init.rb
This avoids uninitialized instance variable warnings.
=> Ensure old_model is defined in FreezeThaw helper module

lib/alexandria/book_providers/worldcat.rb, lib/alexandria/export_library.rb, spec/alexandria/ui/main_app_spec.rb, util/rake/fileinstall.rb
This corrects offenses flagged newly by cops in RuboCop 1.37.0.
- Autocorrect Lint/DuplicateMagicComment
- Autocorrect Style/RedundantStringEscape
- Autocorrect Layout/EmptyLines
=> Correct new RuboCop offenses

.github/workflows/ruby.yml
Recently, GitHub Actions changed ubuntu-latest from 20.04 to 22.04, causing build failures due to changes in apt packages.
Downgrade for now to allow other pull requests to be tested and merged.
=> Keep building on Ubuntu 20.04 for the time being

alexandria-book-collection-manager.gemspec
This dependency is no longer needed since all supported versions of Ruby come with psych 3.1 or later by default. This should be enough to support the yaml features used by alexandria.
=> Drop explicit psych dependency

lib/alexandria/book_providers/z3950_provider.rb
Alexandria's version requirements ensure that the `MARC::Record.new_from_marc` method is available, so do not attempt to use the old interface if it fails.
=> Do not attempt to process MARC using ancient interface

.github/workflows/ruby.yml, alexandria-book-collection-manager.gemspec, lib/alexandria/book_providers/z3950_provider.rb, lib/alexandria/library_store.rb, lib/alexandria/preferences.rb, spec/alexandria/library_collection_spec.rb, spec/alexandria/library_spec.rb, spec/alexandria/library_store_spec.rb
These changes should make the CI build pass. From there, we can start updating dependencies and platforms.
- Pin gstreamer and gtk3 to version 4.0.8
- Fix new RuboCop offenses
- Drop 3.2.0-preview2 build
=> Fix the build

alexandria-book-collection-manager.gemspec
Version 4.0.9 makes the spec runs fail in CI even when no specs fail.
=> Pin gstreamer and gtk3 to version 4.0.8

alexandria-book-collection-manager.gemspec
The alexandria-zoom gem is an updated fork of ruby-zoom.
=> Replace zoom with alexandria-zoom

.github/workflows/ruby.yml, .rubocop.yml, alexandria-book-collection-manager.gemspec, lib/alexandria/book_providers/thalia_provider.rb, lib/alexandria/book_providers/world_cat_provider.rb, lib/alexandria/config.rb, lib/alexandria/library_store.rb, lib/alexandria/models/book.rb, tasks/setup.rb
Ruby 2.7 is EOL and causes regular intermittent core dumps in CI.
Bumping the minimum Ruby version also triggers some new RuboCop offenses, which were corrected.
- Drop support for Ruby 2.7
- Autocorrect Lint/RedundantDirGlobSort
- Autocorrect Style/MutableConstant
- Autocorrect Style/RedundantFreeze
=> Drop support for Ruby 2.7

alexandria-book-collection-manager.gemspec
Version 4.1.6 fixes a TypeError that causes builds in CI to fail for versions 4.0.9 through 4.1.5.
See https://github.com/ruby-gnome/ruby-gnome/commit/3d52996e30b688a36264ca875dc62e768d4837ca
Makes #217 and #218 obsolete.
=> Update gstreamer and gtk3 dependencies to 4.1.6

alexandria-book-collection-manager.gemspec, spec/alexandria/ui/export_dialog_spec.rb
- Bump versions for rubocop dependencies
- Autocorrect RSpec/ReceiveMessages offense
=> Fix new RuboCop offense

lib/alexandria/export_library.rb, lib/alexandria/import_library.rb, lib/alexandria/ui/new_book_dialog_manual.rb, spec/alexandria/export_library_spec.rb
`Dir.tmpdir` simply returns the existing directory for temporary files. This is unsafe. Use `Dir.mktmpdir` instead to get a unique temporary directory each time.
=> Ensure fresh temporary directories are used each time

lib/alexandria/book_providers.rb, lib/alexandria/book_providers/z3950_provider.rb, spec/alexandria/book_providers/z3950_provider_spec.rb, spec/spec_helper.rb
- Raise ConnectionError instead of RuntimeError when ZOOM times out
- Skip provider spec if connection fails
=> Gracefully handle ZOOM timeout in specs

.github/workflows/ruby.yml
Ruby 3.3 has been released so no need to use the preview version anymore.
=> Build with released Ruby 3.3

alexandria-book-collection-manager.gemspec
The previous way of identifying was deprecated. See https://spdx.org/licenses/.
=> Specify the license using the SPDX License List identifier

alexandria-book-collection-manager.gemspec
- Add dependencies that will not be part of Ruby starting from Ruby 3.4
- Add development dependency that will not be part of Ruby from 3.4
=> Add dependencies needed starting from Ruby 3.4

lib/alexandria/book_providers.rb, lib/alexandria/book_providers/thalia_provider.rb, lib/alexandria/book_providers/website_based_provider.rb, lib/alexandria/import_library_csv.rb, lib/alexandria/smart_library.rb, lib/alexandria/ui/multi_drag_treeview.rb, lib/alexandria/ui/new_book_dialog.rb, lib/alexandria/ui/new_book_dialog_manual.rb, lib/alexandria/ui/new_smart_library_dialog.rb, lib/alexandria/ui/preferences_dialog.rb, lib/alexandria/ui/ui_manager.rb
- Autocorrect Style/SuperArguments
- Autocorrect Layout/EmptyComment
- Autocorrect Style/SymbolProc
- Remove iteration whose result was never used
- Fix Style/MapIntoArray offenses
=> Fix new RuboCop offenses

alexandria-book-collection-manager.gemspec
Using add_runtime_dependency is soft-deprecated and now flagged by RuboCop.
=> Replace soft-deprecated runtime dependency specification

.github/workflows/ruby.yml, .rubocop.yml, alexandria-book-collection-manager.gemspec, lib/alexandria/book_providers.rb, lib/alexandria/export_library.rb, lib/alexandria/logging.rb, lib/alexandria/models/book.rb, lib/alexandria/scanners.rb
This drops support for Ruby 3.0 which is EOL.
=> Support Ruby 3.1 through 3.4

.github/workflows/ruby.yml
This means that for now, jobs run on Ubuntu 22.04.
=> Ensure GitHub Actions Runner OS includes gconf2

alexandria-book-collection-manager.gemspec
This changes the minimum required version to 1.3.0 since 1.2.0 contains some bugfixes and 1.3.0 drops support for Ruby 2.2 and hence a dependency on unf.
=> Loosen, simplify and update marc version requirement

.rubocop.yml, Rakefile, alexandria-book-collection-manager.gemspec, lib/alexandria/export_library.rb, lib/alexandria/library_store.rb, lib/alexandria/ui/ui_manager.rb
- Bump rubocop dependencies
- Use the new rubocop plugins configuration syntax
- Fix new RuboCop offenses
=> Update rubocop gems and config, and fix offenses

.github/workflows/ruby.yml, .rubocop.yml, alexandria-book-collection-manager.gemspec, lib/alexandria/book_providers.rb, lib/alexandria/export_format.rb, lib/alexandria/preferences.rb, lib/alexandria/smart_library.rb, util/rake/fileinstall.rb
- **Require Ruby 3.2 or higher**
- **Bump RuboCop target ruby version**
- **Autocorrect Style/ArgumentsForwarding**
- **Autocorrect Lint/RedundantRequireStatement**
- **Remove Ruby 3.1 from the CI matrix**
=> Support Ruby 3.2 and above
