- .travis.yml
- lib/alexandria/preferences.rb
- tasks/spec.rake
- Use xenial distribution
- Use Travis' xvfb servers
- Cache the bundle
> Update Travis configuration

- po/Makefile
> Update Makefile for translations

- .rubocop.yml
- .travis.yml
- alexandria-book-collection-manager.gemspec
- lib/alexandria/book_providers/siciliano.rb
- lib/alexandria/export_library.rb
- lib/alexandria/import_library.rb
- lib/alexandria/ui/acquire_dialog.rb
- lib/alexandria/ui/import_dialog.rb
- lib/alexandria/ui/listview.rb
- lib/alexandria/ui/new_book_dialog.rb
> Drop support for Ruby 2.4

- lib/alexandria.rb
- lib/alexandria/book_providers.rb
- lib/alexandria/book_providers/adlibris.rb
- lib/alexandria/book_providers/amazon_ecs_util.rb
- lib/alexandria/book_providers/barnes_and_noble.rb
- lib/alexandria/book_providers/douban.rb
- lib/alexandria/book_providers/proxis.rb
- lib/alexandria/book_providers/pseudomarc.rb
- lib/alexandria/book_providers/thalia.rb
- lib/alexandria/book_providers/worldcat.rb
- lib/alexandria/export_library.rb
- lib/alexandria/import_library.rb
- lib/alexandria/import_library_csv.rb
- lib/alexandria/preferences.rb
- lib/alexandria/scanners/cue_cat.rb
- lib/alexandria/smart_library.rb
- lib/alexandria/ui.rb
- lib/alexandria/ui/acquire_dialog.rb
- lib/alexandria/ui/book_properties_dialog.rb
- lib/alexandria/ui/icons.rb
- lib/alexandria/ui/iconview_tooltips.rb
- lib/alexandria/ui/import_dialog.rb
- lib/alexandria/ui/listview.rb
- lib/alexandria/ui/multi_drag_treeview.rb
- lib/alexandria/ui/new_book_dialog.rb
- lib/alexandria/ui/preferences_dialog.rb
- lib/alexandria/ui/skip_entry_dialog.rb
- lib/alexandria/ui/sound.rb
- lib/alexandria/ui/ui_manager.rb
- spec/alexandria/book_providers_spec.rb
Debug statements do not need to be translated
- Don't translated text in `log.debug`
- Replace `puts` with `log.debug` and `log.info` as appropriate
> Ease I18n Effort

- .simplecov
- lib/alexandria/smart_library.rb
Implements relevant suggestions from fasterer. Fixes #46.
> Improve operator definitions

- README.md
Preview: https://github.com/HappyFacade/alexandria-book-collection-manager/blob/patch-1/README.md
> Small improvements to readme

- lib/alexandria/export_library.rb
- lib/alexandria/ui/export_dialog.rb
- lib/alexandria/ui/import_dialog.rb
- spec/alexandria/ui/export_dialog_spec.rb
- spec/alexandria/ui/import_dialog_spec.rb
> Fix Import and Export menu action crashes

- README.md
- share/gnome/help/alexandria/C/searching.xml
- share/gnome/help/alexandria/C/settings.xml
- share/gnome/help/alexandria/fr/alexandria.xml
> Remove references to obsolete MCE (Spanish Ministry of Culture) provider

- .github/workflows/ruby.yml
Just adds 3.0 to the CI config.
> Support Ruby 3.0

- .github/workflows/ruby.yml
- Ensure latest apt data are available
- Make list of installations more compact
> Fix apt installations on CI

- lib/alexandria/library_store.rb
- lib/alexandria/models/book.rb
- spec/data/libraries/0.6.2/My Library/9780571147168.yaml
> Filter out Library objects when loading Book from yaml

- lib/alexandria/ui/ui_manager.rb
- spec/alexandria/ui/ui_manager_spec.rb
> Fix selection update when added book does not match current filter

- lib/alexandria/preferences.rb
> Recognize negative integers in GConf settings

- Rakefile
Shared items are not in data/ but in share/ in the project directory.
> Fix source for shared items to install

- spec/alexandria/preferences_spec.rb
- Autocorrect RSpec/BeEq
- Autocorrect RSpec/BeNil
> Fix new RuboCop offenses

- Rakefile
- lib/alexandria.rb
- lib/alexandria/models/library.rb
- lib/alexandria/ui/book_properties_dialog_base.rb
- lib/alexandria/web_themes.rb
- util/rake/fileinstall.rb
This is a new cop that was introduced in RuboCop 1.28.
> Fix Style/FetchEnvVar offenses

- alexandria-book-collection-manager.gemspec
- lib/alexandria/export_library.rb
- lib/alexandria/import_library.rb
- lib/alexandria/library_store.rb
- lib/alexandria/models/library.rb
- lib/alexandria/smart_library.rb
- lib/alexandria/ui/book_properties_dialog_base.rb
- lib/alexandria/ui/icons.rb
- lib/alexandria/ui/ui_manager.rb
- spec/alexandria/export_library_spec.rb
- spec/alexandria/library_spec.rb
- spec/spec_helper.rb
- util/rake/gettextgenerate.rb
- Bump RuboCop version to support new cops
- Autocorrect Lint/NonAtomicFileOperation
- Fix Layout/LineContinuationLeadingSpace offenses
> Update RuboCop and fix new offenses

- .github/workflows/ruby.yml
- Start testing on upcoming Ruby version 3.2
> Add support for Ruby 3.2

- alexandria-book-collection-manager.gemspec
- lib/alexandria/book_providers.rb
- lib/alexandria/logging.rb
- Bump minumum RuboCop dependency versions
- Autocorrect Style/SafeNavigation offenses
> Bump minumum rubocop dependency versions and fix new offenses

- .github/workflows/ruby.yml
- alexandria-book-collection-manager.gemspec
- lib/alexandria/models/library.rb
- lib/alexandria/ui/barcode_animation.rb
- lib/alexandria/ui/new_book_dialog.rb
- Bump minimum rubocop dependency version
- Autocorrect Style/YodaExpression
> Bump rubocop version and fix new offenses

- lib/alexandria/export_library.rb
- spec/alexandria/export_library_spec.rb
- Test exported bibtex contents
- Simplify bibtex authors export
- Simplify bibtex cite key generation
- Inline memoized spec helper
> Simplify BibTeX export implementation

- .github/workflows/ruby.yml
- lib/alexandria/book_providers/website_based_provider.rb
We always want to configure things this way, not just in CI.
> Move Nokogiri memory management setting into the code
